// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var KeyboardEvent = /* module */[];

var Observable = /* module */[];

exports.KeyboardEvent = KeyboardEvent;
exports.Observable = Observable;
/* No side effect */
