// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Baconjs = require("baconjs");

var KeyboardEvent = /* module */[];

function flatMapOption(obs, fn) {
  return obs.flatMap((function (item) {
                var match = Curry._1(fn, item);
                if (match) {
                  return Baconjs.once(match[0]);
                } else {
                  return Baconjs.never();
                }
              }));
}

var Observable = /* module */[/* flatMapOption */flatMapOption];

exports.KeyboardEvent = KeyboardEvent;
exports.Observable = Observable;
/* baconjs Not a pure module */
