// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var getById = (
    function(arg) {
      return document.getElementById(arg);
    }
  );

var getByTagName = (
    function(arg) {
      return document.getElementsByTagName(arg);
    }
  );

exports.getById = getById;
exports.getByTagName = getByTagName;
/* getById Not a pure module */
