// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function add(x, y) {
  return x + y | 0;
}

function getVariantValue(x) {
  if (typeof x === "number") {
    return 0;
  } else if (x.tag) {
    return Caml_format.caml_int_of_string(x[0]) + x[1] | 0;
  } else {
    return x[0];
  }
}

console.log("Hello, BuckleScript and Reason!");

var x = $$Array.map((function (x) {
        return x + 1 | 0;
      }), /* int array */[
      1,
      2,
      3
    ]);

console.log("another thing: ");

console.log(x);

var score = 10;

var variantValue = /* Yes */0;

exports.score = score;
exports.add = add;
exports.variantValue = variantValue;
exports.getVariantValue = getVariantValue;
exports.x = x;
/*  Not a pure module */
