// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function explodeString(s) {
  var s$1 = s;
  var _idx = s.length - 1 | 0;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var idx = _idx;
    if (idx === -1) {
      return acc;
    } else {
      var c = Caml_string.get(s$1, idx);
      _acc = /* :: */[
        c,
        acc
      ];
      _idx = idx - 1 | 0;
      continue ;
      
    }
  };
}

function unfold(f, seed) {
  var _current = seed;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var current = _current;
    var match = Curry._1(f, current);
    if (match) {
      var match$1 = match[0];
      _acc = /* :: */[
        match$1[0],
        acc
      ];
      _current = match$1[1];
      continue ;
      
    } else {
      return List.rev(acc);
    }
  };
}

exports.explodeString = explodeString;
exports.unfold = unfold;
/* No side effect */
