// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Util$Crosswords = require("../src/Util.bs.js");

describe("isAlpha", (function () {
        return Jest.testAll("all", /* :: */[
                    /* tuple */[
                      "a",
                      /* true */1
                    ],
                    /* :: */[
                      /* tuple */[
                        "D",
                        /* true */1
                      ],
                      /* :: */[
                        /* tuple */[
                          "-",
                          /* false */0
                        ],
                        /* :: */[
                          /* tuple */[
                            ".",
                            /* false */0
                          ],
                          /* :: */[
                            /* tuple */[
                              "",
                              /* false */0
                            ],
                            /* :: */[
                              /* tuple */[
                                " ",
                                /* false */0
                              ],
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ], (function (param) {
                      return Jest.Expect[/* toEqual */12](param[1], Jest.Expect[/* expect */0](Util$Crosswords.isAlpha(param[0])));
                    }));
      }));

/*  Not a pure module */
